[workspace]
members = ["bma423-async", "gdeh0154d67-async"]

[package]
name = "watchy-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
hal = { package = "esp32-hal", version = "0.12.0", features = ["async", "embassy", "embassy-time-timg0"] }
esp-backtrace = { version = "0.7.0", features = ["esp32", "panic-handler", "exception-handler", "print-uart"] }
esp-println = { version = "0.5.0", features = ["esp32"] }
static_cell = "1.1.0"
embassy-executor = { version = "0.2.0", features = ["nightly", "arch-xtensa", "executor-thread", "integrated-timers"] }
embassy-time = { version = "0.1.1", features = ["nightly"] }
